const users = [
  {
    _id: "1",
    username: "user1",
    name: "user one",
    password: "password1",
    profilePicture: "profile1.jpg",
    gender: "male",
  },
  {
    _id: "2",
    username: "user2",
    name: "user two",
    password: "password2",
    profilePicture: "profile2.jpg",
    gender: "male",
  },
  {
    _id: "3",
    username: "user3",
    name: "user three",
    password: "password3",
    profilePicture: "profile3.jpg",
    gender: "male",
  },
];
const transactions = [
  {
    _id: "1",
    userId: "1",
    description: "Transaction three",
    paymentType: "CASH",
    category: "Category three",
    amount: 250.0,
    location: "Location three",
    data: "2024-02-15",
  },
  {
    _id: "2",
    userId: "2",
    description: "Transaction three",
    paymentType: "CARD",
    category: "Category three",
    amount: 2501.0,
    location: "Location three",
    data: "2024-02-15",
  },
  {
    _id: "3",
    userId: "3",
    description: "Transaction three",
    paymentType: "CASH",
    category: "Category three",
    amount: 212350.0,
    location: "Location three",
    data: "2024-02-15",
  },
  {
    _id: "4",
    userId: "1",
    description: "Transaction four",
    paymentType: "CARD",
    category: "Category four",
    amount: 12011.0,
    location: "Location four",
    data: "2024-03-02",
  },
  {
    _id: "5",
    userId: "2",
    description: "Transaction five",
    paymentType: "CARD",
    category: "Category five",
    amount: 82300.0,
    location: "Location five",
    data: "2024-04-10",
  },
  {
    _id: "6",
    userId: "3",
    description: "Transaction six",
    paymentType: "CARD",
    category: "Category six",
    amount: 352430.0,
    location: "Location six",
    data: "2024-05-20",
  },
];
export { users, transactions };
